language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t hryhorii/docker-react -f Dockerfile.dev .  

script:
  - docker run -e CI=true hryhorii/docker-react npm run test  